# Changes here may be overwritten by Copier.
_commit: a3cac90
_src_path: /home/_404/src/uvt
author_email: _404@example.com
author_name: _404
description: POC for CPython Lib adapters and Python tooling.
distribution_name: sdk-feedback
github_owner: _404
import_package_name: sdk_feedback
license: MIT
publish_to_pypi: false
